-- Create table for storing boarding room chat messages
CREATE TABLE IF NOT EXISTS boarding_room_chat (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  group_id UUID NOT NULL,
  user_id UUID NOT NULL,
  user_email TEXT NOT NULL,
  message TEXT NOT NULL,
  is_system BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  
  FOREIGN KEY (group_id) REFERENCES trust_groups(id) ON DELETE CASCADE,
  FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE
);

-- Add indexes for faster queries
CREATE INDEX IF NOT EXISTS idx_boarding_room_chat_group_id ON boarding_room_chat(group_id);
CREATE INDEX IF NOT EXISTS idx_boarding_room_chat_user_id ON boarding_room_chat(user_id);
CREATE INDEX IF NOT EXISTS idx_boarding_room_chat_created_at ON boarding_room_chat(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_boarding_room_chat_group_created ON boarding_room_chat(group_id, created_at DESC);

-- Enable Row Level Security
ALTER TABLE boarding_room_chat ENABLE ROW LEVEL SECURITY;

-- RLS Policy: Users can only view messages from groups they're members of
CREATE POLICY "Users can view messages from their groups"
  ON boarding_room_chat FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM trust_group_members
      WHERE trust_group_members.group_id = boarding_room_chat.group_id
      AND trust_group_members.user_id = auth.uid()
    )
  );

-- RLS Policy: Users can only insert their own messages
CREATE POLICY "Users can insert their own messages"
  ON boarding_room_chat FOR INSERT
  WITH CHECK (auth.uid() = user_id);

-- RLS Policy: Users cannot update messages (immutable)
CREATE POLICY "Messages are immutable"
  ON boarding_room_chat FOR UPDATE
  USING (FALSE);

-- RLS Policy: Users can only delete their own messages
CREATE POLICY "Users can delete their own messages"
  ON boarding_room_chat FOR DELETE
  USING (auth.uid() = user_id);

-- Create trigger to update updated_at timestamp
CREATE OR REPLACE FUNCTION update_boarding_room_chat_timestamp()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS boarding_room_chat_update_timestamp ON boarding_room_chat;
CREATE TRIGGER boarding_room_chat_update_timestamp
  BEFORE UPDATE ON boarding_room_chat
  FOR EACH ROW
  EXECUTE FUNCTION update_boarding_room_chat_timestamp();
