-- ================================================================
-- SELF-SERVICE ACCOUNT DELETION — emailed magic link
-- Run once in the Supabase SQL Editor.
--
-- Mirrors PIN_RESET_EMAIL_SELFSERVICE.sql's shape for the Danger Zone's
-- "Delete Account" action: the Danger Zone panel (MobileView.jsx) no longer
-- deletes on the spot from a typed password. Instead the user types their
-- registered Gmail address and the literal phrase "delete my account" to
-- confirm, which asks the trusted Express backend (backend/routes/
-- emailRoutes.js, POST /api/email/request-account-deletion, service-role
-- key, verifies the caller's Supabase session and that the typed email/
-- phrase match first) to email a one-time deletion link to that address.
-- Only opening that link (ConfirmDeleteAccountPage.jsx -> the delete-account
-- edge function) actually deletes anything — so recording an intent to
-- delete is no longer, on its own, proof the account's own inbox was ever
-- involved.
--
-- Same raw-token-never-in-the-response discipline as PIN_RESET_EMAIL_
-- SELFSERVICE.sql: the raw token is generated by the Express backend and is
-- ONLY ever placed inside the emailed link. Only a SHA-256 hash of it is
-- stored here, so even reading this table can't produce a usable token.
-- Redeeming it (in the delete-account edge function) requires possessing
-- the raw token from the email itself, single-use, 30-minute expiry.
-- ================================================================

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS public.account_deletion_tokens (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  token_hash text NOT NULL UNIQUE,
  expires_at timestamptz NOT NULL,
  used_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_account_deletion_tokens_user ON public.account_deletion_tokens(user_id);
CREATE INDEX IF NOT EXISTS idx_account_deletion_tokens_hash ON public.account_deletion_tokens(token_hash);

ALTER TABLE public.account_deletion_tokens ENABLE ROW LEVEL SECURITY;
-- No SELECT/INSERT/UPDATE policy for anon/authenticated at all — every write
-- comes from the Node backend or the delete-account edge function using the
-- service-role key (bypasses RLS). The raw token, not a database row, is the
-- actual credential a client can act on, so no client-facing policy is
-- needed or wanted here.

SELECT 'Self-service account deletion (email link) installed — request-account-deletion stays in backend/routes/emailRoutes.js, redemption stays in the delete-account edge function.' AS status;
