-- ================================================================
-- SELF-SERVICE PIN RESET — emailed magic link
-- Run once in the Supabase SQL Editor.
--
-- This is a SECOND, alternative path to PIN_RECOVERY_AND_ACCOUNT_UNLOCK.sql's
-- dev-reviewed flow (PINRecoveryModal.jsx "Request developer review" /
-- ICANDevPanel.jsx Recovery tab) — that flow is untouched by this file and
-- still works exactly as before. This adds "email me a reset link", mirroring
-- how Forgot Password works on the sign-in page (AuthContext.jsx
-- resetPasswordForEmail): prove you own the registered email, then set a
-- new PIN yourself.
--
-- IMPORTANT — this does NOT reintroduce the bug that PIN_RECOVERY_AND_
-- ACCOUNT_UNLOCK.sql deliberately removed. That earlier design handed the
-- raw unlock_token straight back to the requesting browser tab, so the same
-- client that asked for "review" could immediately redeem it itself — no
-- email ever required. Here the raw token is generated by the trusted
-- Express backend (backend/routes/emailRoutes.js, POST /request-pin-reset,
-- service-role key, verifies the caller's Supabase session first) and is
-- ONLY ever placed inside the emailed link — it is never returned in that
-- endpoint's HTTP response. Only a SHA-256 hash of it is stored here, so
-- even reading this table can't produce a usable token. Redeeming (this
-- file's redeem_pin_reset_token) requires possessing the raw token from the
-- email itself, single-use, 30-minute expiry.
-- ================================================================

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS public.pin_reset_tokens (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  token_hash text NOT NULL UNIQUE,
  expires_at timestamptz NOT NULL,
  used_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_pin_reset_tokens_user ON public.pin_reset_tokens(user_id);
CREATE INDEX IF NOT EXISTS idx_pin_reset_tokens_hash ON public.pin_reset_tokens(token_hash);

ALTER TABLE public.pin_reset_tokens ENABLE ROW LEVEL SECURITY;
-- No SELECT/INSERT/UPDATE policy for anon/authenticated at all — every write
-- comes from the Node backend using the service-role key (bypasses RLS), and
-- the only read path is inside redeem_pin_reset_token() below (SECURITY
-- DEFINER). The raw token, not a database row, is the actual credential a
-- client can act on, so no client-facing policy is needed or wanted here.

-- ============================================================
-- Redeem a token from the emailed link, setting a new PIN.
-- Callable by anon: the browser tab that opens the link may not carry an
-- authenticated Supabase session at all (different device/browser) — the
-- token itself, sent only to the account's registered email, is the proof
-- of ownership, exactly like Supabase's own password-recovery link.
-- ============================================================
DROP FUNCTION IF EXISTS public.redeem_pin_reset_token(text, text);

CREATE OR REPLACE FUNCTION public.redeem_pin_reset_token(
  p_token text,
  p_new_pin_hash text
)
RETURNS TABLE (success boolean, message text)
SECURITY DEFINER SET search_path = public LANGUAGE plpgsql AS $$
DECLARE
  v_token_hash text;
  v_row record;
BEGIN
  IF p_token IS NULL OR length(p_token) < 32 OR p_new_pin_hash IS NULL OR p_new_pin_hash = '' THEN
    RETURN QUERY SELECT false, 'Invalid request.'::text;
    RETURN;
  END IF;

  v_token_hash := encode(digest(p_token, 'sha256'), 'hex');

  SELECT * INTO v_row
  FROM public.pin_reset_tokens
  WHERE token_hash = v_token_hash
    AND used_at IS NULL
    AND expires_at > now()
  LIMIT 1;

  IF v_row IS NULL THEN
    RETURN QUERY SELECT false, 'This reset link is invalid or has expired. Request a new one.'::text;
    RETURN;
  END IF;

  -- user_id isn't unique on user_accounts (personal + business rows can
  -- coexist) — reset every account owned by the user, same reasoning as
  -- ican_dev_resolve_recovery_request() in PIN_RECOVERY_AND_ACCOUNT_UNLOCK.sql.
  UPDATE public.user_accounts
  SET pin_hash = p_new_pin_hash,
      pin_attempts = 0,
      pin_locked_until = NULL,
      failed_pin_attempts = 0,
      updated_at = now()
  WHERE user_id = v_row.user_id;

  UPDATE public.pin_reset_tokens
  SET used_at = now()
  WHERE id = v_row.id;

  -- Burn any other still-live tokens for this user so an older emailed link
  -- can't be replayed after a newer one was already used.
  UPDATE public.pin_reset_tokens
  SET used_at = now()
  WHERE user_id = v_row.user_id AND used_at IS NULL;

  RETURN QUERY SELECT true, 'PIN reset — sign in with your new PIN.'::text;
EXCEPTION WHEN OTHERS THEN
  RETURN QUERY SELECT false, 'Error: ' || SQLERRM;
END;
$$;

GRANT EXECUTE ON FUNCTION public.redeem_pin_reset_token(text, text) TO anon, authenticated;

SELECT 'Self-service PIN reset (email link) installed — request-pin-reset stays in backend/routes/emailRoutes.js.' AS status;
