-- ================================================================
-- EMAIL VERIFICATION BEFORE FIRST-TIME PIN CREATION
-- Run once in the Supabase SQL Editor.
--
-- Mirrors PIN_RESET_EMAIL_SELFSERVICE.sql's shape but for account
-- creation: before a user can set their wallet PIN for the first time
-- (personal or business — ICANWallet.jsx's two "Create Account" forms),
-- they must enter a 6-digit code emailed to the address they typed in
-- the form. A short typed code (not a link) is used here instead of a
-- magic link because account creation is a multi-field in-page form —
-- redirecting away to a link-landing page would lose the name/phone
-- fields already filled in.
--
-- Same trust model as the reset flow: the code is generated by the
-- trusted Express backend (backend/routes/emailRoutes.js,
-- POST /request-account-otp, service-role key, verifies the caller's
-- Supabase session first); only its SHA-256 hash is stored here.
-- Verification (verify_account_creation_otp) is rate-limited — 5 wrong
-- guesses burns the code — since a 6-digit code has far less entropy
-- than the reset flow's 256-bit token.
-- ================================================================

CREATE TABLE IF NOT EXISTS public.account_creation_otps (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  email text NOT NULL,
  account_type text NOT NULL DEFAULT 'personal' CHECK (account_type IN ('personal', 'business')),
  code_hash text NOT NULL,
  expires_at timestamptz NOT NULL,
  used_at timestamptz,
  attempts int NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_account_creation_otps_user ON public.account_creation_otps(user_id, account_type);

ALTER TABLE public.account_creation_otps ENABLE ROW LEVEL SECURITY;
-- No client-facing policies — every write is either the Node backend using
-- the service-role key (issuing a code) or verify_account_creation_otp()
-- below (SECURITY DEFINER, checking a code the client only ever sees
-- because it was emailed to them).

DROP FUNCTION IF EXISTS public.verify_account_creation_otp(uuid, text, text);

CREATE OR REPLACE FUNCTION public.verify_account_creation_otp(
  p_user_id uuid,
  p_account_type text,
  p_code text
)
RETURNS TABLE (success boolean, message text)
SECURITY DEFINER SET search_path = public LANGUAGE plpgsql AS $$
DECLARE
  v_row record;
  v_code_hash text;
BEGIN
  IF auth.uid() IS NULL OR auth.uid() != p_user_id THEN
    RETURN QUERY SELECT false, 'Not authorized.'::text;
    RETURN;
  END IF;

  IF p_code IS NULL OR p_code !~ '^\d{6}$' THEN
    RETURN QUERY SELECT false, 'Enter the 6-digit code from your email.'::text;
    RETURN;
  END IF;

  SELECT * INTO v_row
  FROM public.account_creation_otps
  WHERE user_id = p_user_id
    AND account_type = p_account_type
    AND used_at IS NULL
    AND expires_at > now()
  ORDER BY created_at DESC
  LIMIT 1;

  IF v_row IS NULL THEN
    RETURN QUERY SELECT false, 'No active code — request a new one.'::text;
    RETURN;
  END IF;

  IF v_row.attempts >= 5 THEN
    RETURN QUERY SELECT false, 'Too many incorrect attempts — request a new code.'::text;
    RETURN;
  END IF;

  v_code_hash := encode(digest(p_code, 'sha256'), 'hex');

  IF v_code_hash != v_row.code_hash THEN
    UPDATE public.account_creation_otps SET attempts = attempts + 1 WHERE id = v_row.id;
    RETURN QUERY SELECT false, ('Incorrect code. ' || (4 - v_row.attempts) || ' attempts left.')::text;
    RETURN;
  END IF;

  UPDATE public.account_creation_otps SET used_at = now() WHERE id = v_row.id;

  RETURN QUERY SELECT true, 'Email verified.'::text;
EXCEPTION WHEN OTHERS THEN
  RETURN QUERY SELECT false, 'Error: ' || SQLERRM;
END;
$$;

GRANT EXECUTE ON FUNCTION public.verify_account_creation_otp(uuid, text, text) TO authenticated;

SELECT 'Signup email OTP verification installed.' AS status;
